### ISSUE TITLE
Instructions misunderstand

### ISSUE THREAD

**Issue by gomesar** [necst/arancino#1]
Hello, 
I'm a little confused about the moment which the `C:\pin` folder have to be created.
> 2- Unzip PIN to the root directory and rename the folder to pin

according to this, the folder `C:\pin` must contain Pin files (pin.exe, docs, extras, ia32, intel64, source), right?
but, here we got another folder creation (I believe that is in the step two, anyway).
> 8- **Create** a folder C:\pin and [...]

The steps 4, 5, and 6 related `PINdemonium/ScyllaDependencies/`, but the `.rar` files are in `ScyllaDependencies/`. 
> Extract the archive in PINdemonium/ScyllaDependencies/diStorm.rar into PINdemonium/Scylla/
> Extract the archive in PINdemonium/ScyllaDependencies/tinyxml.rar into PINdemonium/Scylla/
> Extract the archive in PINdemonium/ScyllaDependencies/WTL.rar into PINdemonium/Scylla/

Another question is where do I must clone this repository? inside `C:\pin`? Or the output is already pointing to this folder?

Thanks, and congratulations for the work.

**Comment by JinBlack** [comment]
Hi gomesar, 
Sorry for the late response.

> according to this, the folder C:\pin must contain Pin files (pin.exe, docs, extras, ia32, intel64, source), right?

Right!

> but, here we got another folder creation

Yes It is the same folder you do not need to recreate it.

> The steps 4, 5, and 6 related PINdemonium/ScyllaDependencies/, but the .rar files are in ScyllaDependencies/.

I'll fix this in the guide. :D

> Another question is where do I must clone this repository? inside C:\pin? Or the output is already pointing to this folder?

You can clone it where you want to compile the project.  What is important is that at the end of compilation process you have the `PINdemonium.dll` file inside `C:\pin` folder.
